### ISSUE TITLE
Class 'Leafo\ScssPhp\Compiler' not found

### ISSUE THREAD

**Issue by metalicaruz** [JoomShaper/helix-ultimate#109]
I'm getting this message after the update:

Class 'Leafo\ScssPhp\Compiler' not found

**Comment by Mike92115** [comment]
Getting the same thing, with PHP 8 and PHP 7.4.  Nothing else other than JCE Pro 2.9.2 has been installed on my Joomla 4 site.

**Comment by metalicaruz** [comment]
> Getting the same thing, with PHP 8 and PHP 7.4. Nothing else other than JCE Pro 2.9.2 has been installed on my Joomla 4 site. System info is attached.
> 
> [systeminfo-2021-01-29T10_34_26-08_00.txt](https://github.com/JoomShaper/helix-ultimate/files/5895626/systeminfo-2021-01-29T10_34_26-08_00.txt)

I already uninstalled the update, I'll wait for it to be fixed.

**Comment by joomleb** [comment]
I confirm the BUG, here [a complete image](https://photos.app.goo.gl/9FpkNshc8ffhk8Yi6)
A temporally workaround is to switch off the "Advanced > SCSS > Compress SCSS to CSS"

+ the [Header logo image / modules are doubled](https://photos.app.goo.gl/qG1cDXa3Kbkqtgei7) - you can see [in action here](https://test2.egulp.net/)

+ during an update, the "Basic > Footer > Go to Top" is switched on automatically

**Comment by ahamed** [comment]
Hello guys,
We've fixed the issue
> Class 'Leafo\ScssPhp\Compiler' not found

Please download the package from the [Github Release](https://github.com/JoomShaper/helix-ultimate/releases/tag/v2.0.0-alpha.4) and install it again.

**Note: Please don't test it on php8. This is not compatible with php8 till now.**

**Comment by ahamed** [comment]
Hello @metalicaruz, @joomleb
Is it solved your problem? If so, then we can close the issue.
Thanks.

**Comment by joomleb** [comment]
Hi @ahamed 
I redownloaded and tested, and for me **all the 5 bugs I reported here** are still there, **NOT solved**.

Point 1 and 5:
- "Advanced > SCSS > Compress SCSS to CSS"
- "Basic > Footer > Go to Top"
are always switched on automatically when installing

Point 1: now there is no crash when installing, but when saving the frontend template still crash as reported

PS When solved would be good to have an Alpha 4.1 or 5 release to don't generate confusion

**Comment by Mike92115** [comment]
Still not working for me either, I installed it and still had the problem. I then un-installed the template, and made sure there was no files hanging around and re-installed and the problem is still there.

**Comment by metalicaruz** [comment]
Still not working for me either.

**Comment by ahamed** [comment]
[2.0.0-alpha.4.zip](https://github.com/JoomShaper/helix-ultimate/files/5930389/2.0.0-alpha.4.zip)
Please try this out.

**Comment by joomleb** [comment]
hI @ahamed 
re-tested on last Alpha 4:

1 - By install / update to last Alpha 4 the frontend does not crash anymore, but:
the "Advanced > SCSS > Compress SCSS to CSS" is always pushed and kept to switch On. If I switch off and Save, _nothing happen_
 
2 - the Header logo image / modules are doubled - you can see [in action here](https://test2.egulp.net/)

3 - the Offcanvas is appended below the Header causing an obliuous movement on open / close

4 - the Header is added on top of the page without moving down the page

5 - during an update, the "Basic > Footer > Go to Top" is always switched on automatically. If I switch off and Save, _nothing happen_

Please, Can you confirm and fix them ?

**Comment by ahamed** [comment]
Hey @joomleb,
The issue was about
>Class 'Leafo\ScssPhp\Compiler' not found

For your problems please raise a separate issue so that we can solve them separately.

**Comment by joomleb** [comment]
Hi @ahamed 
I'm going to open them, Anyway about the first point:

1 - By install / update to last Alpha 4 the frontend does not crash anymore, but the "Advanced > SCSS > Compress SCSS to CSS" is always pushed and kept to switch On. If I switch off and Save, nothing happen . It is always saved as switched on.
The same thing is happening for point 5.
Do I have to open a new report also for that ?

**Comment by ahamed** [comment]
I've noticed the problem. This will be fixed at `alpha.5`. You can raise your issues.
