### ISSUE TITLE
Error when using separator link in submenu

### ISSUE THREAD

**Issue by mojeweb** [JoomShaper/helix-ultimate#293]
### Steps to reproduce the issue

Create submenu type separator and use Joomla Link type/Link image.

### Expected result

Image visible next to separator link.

### Actual result

Error: 0 cannot access protected property Joomla\CMS\Menu\MenuItem::$params

### System information (as much as possible)

Joomla 4.15 and HU 2.0.9

**Comment by mi-prakash** [comment]
@mojeweb 
We have found the issue. Hopefully in future updates there will be a fix for this
Thank you for your feedback

**Comment by MarcelSchuermann** [comment]
I have the same Issue with new Version of Joomla & Helix - see this issue: 
#244

**Comment by mi-prakash** [comment]
@MarcelSchuermann 
these issue will be foxed on next update
thanks

**Comment by joomleb** [comment]
Hi,
[Helix Ultimate 2.0.12](https://www.joomshaper.com/downloads/template/helixultimate) has been release with this fix included.

@mojeweb 
Please, Can you confirm that is run as expected and that the ticket can be closed ?!?

**Comment by mojeweb** [comment]
@joomleb image now shows ok.
Image class is not working (not present in html). 
Select Link image, then enter some class for that image.

**Comment by mi-prakash** [comment]
This issue has been fixed

**Comment by joomleb** [comment]
@mi-prakash 
as far as I read:
"...Image class is not working (not present in html).
Select Link image, then enter some class for that image..."

@mojeweb reported an image class issue.
Please, Can you check it ?

**Comment by joomleb** [comment]
@mi-prakash 
2.0.16 Please, Are this and the #244 been fixed or not?

**Comment by mi-prakash** [comment]
then i'm closing the issue

**Comment by mojeweb** [comment]
Image class still not working. Just try add image class in menu item and see result in html.

**Comment by mi-prakash** [comment]
@mojeweb can u give us a screencast here

**Comment by mojeweb** [comment]
![image](https://github.com/JoomShaper/helix-ultimate/assets/45881772/de3541d8-b10b-4b05-b757-85de3b7c29ba)

This is html
<img data-src="/images/ico/zbirka-osebno-icom.png" alt="Zbirka Osebno" class=" ls-is-cached lazyloaded" src="/images/ico/zbirka-osebno-icom.png">

**Comment by joomleb** [comment]
@mi-prakash 
Looking into this bug would be good to take a look also to these two #347 - #348 images managing related issues...

**Comment by joomleb** [comment]
@mojeweb Will it include a fixing to these two https://github.com/JoomShaper/helix-ultimate/issues/347 - https://github.com/JoomShaper/helix-ultimate/issues/348 images managing related issues ?

**Comment by mi-prakash** [comment]
@joomleb These are not related issue with this thread
